[package]
name = "password-generator-pro"
version = "0.0.0"
description = "A fast, simple and powerful open-source cross platform utility tool for generating strong, unique and random passwords."
authors = ["Sebastien Rousseau"]
license = "MIT"
repository = "https://github.com/sebastienrousseau/password-generator-pro"
default-run = "password-generator-pro"
edition = "2021"
rust-version = "1.57"

[build-dependencies]
tauri-build = { version = "1.2.0", features = [] }

[dependencies]
serde_json = "1.0"
serde = { version = "1.0.147", features = ["derive"] }
tauri = { version = "1.2.0", features = ["api-all", "system-tray"] }
rand = "0.8.5"
convert_case = "0.6.0"
bcrypt = "0.13.0"
chrono = "0.4.23"

[features]
# by default Tauri runs in production mode
# when `tauri dev` runs it is executed with `cargo run --no-default-features` if `devPath` is an URL
default = [ "custom-protocol" ]
# this feature is used used for production builds where `devPath` points to the filesystem
# DO NOT remove this
custom-protocol = [ "tauri/custom-protocol" ]
