name: Build Password Generator Pro

on:
  push:
    branches: [main]

  pull_request:
    branches: [main]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  publish-tauri:
    strategy:
      fail-fast: false

      matrix:
        platform: [macos-latest, ubuntu-20.04, windows-latest]

    runs-on: ${{ matrix.platform }}

    steps:
      - name: ✅ Checkout
        uses: actions/checkout@v2

      - name: ✅ Setup pNpM
        uses: pnpm/action-setup@v2.2.4
        with:
          version: 7

      - name: ✅ Setup Node.js 16
        uses: actions/setup-node@v2
        with:
          node-version: 16
          cache: "pnpm"

      - name: ✅ Install Rust stable
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable

      - name: ✅ Install dependencies (ubuntu only)
        if: matrix.platform == 'ubuntu-20.04'
        run: |
          sudo apt update
          sudo apt upgrade -y
          sudo apt install -y \
              build-essential \
              curl \
              libasound2-dev \
              libayatana-appindicator3-dev \
              libgtk-3-dev \
              librsvg2-dev \
              libwebkit2gtk-4.0-dev \
              patchelf \
              wget \

      # - name: Cache cargo registry
      #   uses: actions/cache@v2
      #   with:
      #     path: ~/.cargo/registry

      #     # Add date to the cache to keep it up to date
      #     key: ${{ matrix.platform }}-stable-cargo-registry-${{ hashFiles('**/Cargo.toml') }}-${{ env.CURRENT_DATE }}

      #     # Restore from outdated cache for speed
      #     restore-keys: |
      #       ${{ matrix.platform }}-stable-cargo-registry-${{ hashFiles('**/Cargo.toml') }}
      #       ${{ matrix.platform }}-stable-cargo-registry-

      # - name: Cache cargo index
      #   uses: actions/cache@v2
      #   with:
      #     path: ~/.cargo/git

      #     # Add date to the cache to keep it up to date
      #     key: ${{ matrix.platform }}-stable-cargo-index-${{ hashFiles('**/Cargo.toml') }}-${{ env.CURRENT_DATE }}

      #     # Restore from outdated cache for speed
      #     restore-keys: |
      #       ${{ matrix.platform }}-stable-cargo-index-${{ hashFiles('**/Cargo.toml') }}
      #       ${{ matrix.platform }}-stable-cargo-index-
      # - name: Cache core cargo target
      #   uses: actions/cache@v2
      #   with:
      #     path: target

      #     # Add date to the cache to keep it up to date
      #     key: ${{ matrix.platform }}-stable-cargo-core-${{ hashFiles('core/**/Cargo.toml') }}-${{ env.CURRENT_DATE }}

      #     # Restore from outdated cache for speed
      #     restore-keys: |
      #       ${{ matrix.platform }}-stable-cargo-core-${{ hashFiles('core/**/Cargo.toml') }}
      #       ${{ matrix.platform }}-stable-cargo-core-

      # - name: ✅ Run tests
      # run: pnpm run test

      - name: ✅ Install pNpM dependencies
        run: pnpm install --frozen-lockfile

      - name: ✅ Build
        run: pnpm run build

      # - name: ✅ Build
      #   run: cd src-tauri && cargo build --verbose

      # - name: ✅ Run Cargo tests
      #   run: cd src-tauri && cargo test --verbose

      - name: ✅ Publish
        uses: tauri-apps/tauri-action@v0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          TAURI_KEY_PASSWORD: ${{ secrets.TAURI_KEY_PASSWORD }}
          TAURI_PRIVATE_KEY: ${{ secrets.TAURI_PRIVATE_KEY }}
          TAURI_PUBLIC_KEY: ${{ secrets.TAURI_PUBLIC_KEY }}
        with:
          tagName: password-generator-pro-v__VERSION__ # the action automatically replaces \_\_VERSION\_\_ with the app version
          releaseName: "Password Generator v__VERSION__"
          releaseBody: "See the assets to download this version and install."
          releaseDraft: true
          prerelease: false
