name: Password Generator Pro

on:
  pull_request:
    branches:
      - "*"
  push:
    branches:
      - "*"

env:
  APP_NAME: "password-generator-pro"

jobs:
  publish-tauri:
    strategy:
      fail-fast: false

      matrix:
        platform: [macos-latest, ubuntu-20.04]

    runs-on: ${{ matrix.platform }}

    steps:
      - name: ✅ Checkout code (main branch)
        uses: actions/checkout@v3

      - name: ✅ Setup pNpM 7
        uses: pnpm/action-setup@v2
        with:
          version: 7
          run_install: false

      - name: ✅ Get pnpm store directory
        id: pnpm-cache
        shell: bash
        run: |
          echo "STORE_PATH=$(pnpm store path)" >> $GITHUB_OUTPUT

      - name: ✅ Setup pnpm cache
        uses: actions/cache@v3
        with:
          path: ${{ steps.pnpm-cache.outputs.STORE_PATH }}
          key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-store-

      - name: ✅ Setup Node.js 16
        uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: "pnpm"

      - name: ✅ Install Rust stable toolchain
        uses: dtolnay/rust-toolchain@stable

      - name: ✅ Install dependencies (ubuntu only)
        if: matrix.platform == 'ubuntu-20.04'
        run: |
          sudo apt update
          sudo apt upgrade -y
          sudo apt install -y \
              build-essential \
              curl \
              libasound2-dev \
              libayatana-appindicator3-dev \
              libgtk-3-dev \
              librsvg2-dev \
              libwebkit2gtk-4.0-dev \
              patchelf \
              wget \

      - name: ✅ Install dependencies
        run: pnpm install --frozen-lockfile

      - name: ✅ Building
        run: pnpm run build -- --verbose

      - name: ✅ Publishing
        uses: tauri-apps/tauri-action@v0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          args: --verbose
          tagName: ${{ env.APP_NAME }}-v__VERSION__ # the action automatically replaces \_\_VERSION\_\_ with the app version
          releaseName: "Password Generator Pro v__VERSION__"
          releaseBody: "👋 Welcome to Password Generator Pro (v__VERSION__).\n\n\nSee the assets to download this version and install."
          releaseDraft: true
          prerelease: false
