name: Build, Test and Publish to Crates.io
on: [push, pull_request]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        platform: [macos-latest, ubuntu-latest, windows-latest]

    runs-on: ${{ matrix.platform }}

    steps:
      - uses: actions/checkout@v3
      - name: install dependencies (ubuntu only)
        if: matrix.platform == 'ubuntu-latest'
        run: |
          sudo apt update
          sudo apt install -y libwebkit2gtk-4.0-dev \
              build-essential \
              curl \
              wget \
              libssl-dev \
              libgtk-3-dev \
              libayatana-appindicator3-dev \
              librsvg2-dev
      - name: Build
        run: cd src-tauri && cargo build --verbose
      - name: Run tests
        run: cd src-tauri && cargo test --verbose
      - name: Publish
        run: cd src-tauri && cargo publish --token ${{ CARGO_TOKEN }}
