name: Build Password Generator Pro

on:
  - push
  - pull_request
  - workflow_dispatch

env:
  APP_NAME: "password-generator-pro"

jobs:
  publish-tauri:
    strategy:
      fail-fast: false

      matrix:
        platform: [macos-latest, ubuntu-20.04, windows-latest]

    runs-on: ${{ matrix.platform }}

    steps:
      - name: ✅ Checkout
        uses: actions/checkout@v3

      - name: ✅ Setup pNpM
        uses: pnpm/action-setup@v2
        with:
          version: 7

      - name: ✅ Setup Node.js 16
        uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: "pnpm"

      - name: ✅ Install Rust stable
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable

      - name: ✅ Install dependencies (ubuntu only)
        if: matrix.platform == 'ubuntu-20.04'
        run: |
          sudo apt update
          sudo apt upgrade -y
          sudo apt install -y \
              build-essential \
              curl \
              libasound2-dev \
              libayatana-appindicator3-dev \
              libgtk-3-dev \
              librsvg2-dev \
              libwebkit2gtk-4.0-dev \
              patchelf \
              wget \

      - name: ✅ Install pNpM dependencies
        run: pnpm install --frozen-lockfile

      - name: ✅ Build
        run: pnpm run build

      - name: ✅ Publish
        uses: tauri-apps/tauri-action@v0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tagName: ${{ env.APP_NAME }}-v__VERSION__ # the action automatically replaces \_\_VERSION\_\_ with the app version
          releaseName: "Password Generator v__VERSION__"
          releaseBody: "👋 Welcome to Password Generator Pro (v__VERSION__).\n\nThis is a new release of Password Generator Pro with the following changes:\n\n- __CHANGELOG__"
          releaseDraft: true
          prerelease: false
