name: "Build Password Generator Pro"

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build-binaries:
    name: "${{ matrix.platform.target }}"

    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]
        node-version: [16.x]
        rust_version: [stable]

        platform:
          # Windows
          - { id: windows, target: x86_64-pc-windows-msvc, os: windows-latest }
          - { id: windows, target: aarch64-pc-windows-msvc, os: windows-latest }

          # Ubuntu
          - { id: ubuntu, target: x86_64-unknown-linux-gnu, os: ubuntu-latest }

          # macOS
          - { id: macos, target: x86_64-apple-darwin, os: macos-latest }
          - { id: macos, target: aarch64-apple-darwin, os: macos-latest }

    env:
      APP_VERSION: "0.0.1"
      CARGO_INCREMENTAL: 0
      CARGO_TERM_COLOR: always
      CMD: ${{ matrix.platform.cmd }}
      FEATURES: ${{ format(',{0}', matrix.platform.features ) }}
      OPTIONS: ${{ matrix.platform.options }}
      OS: ${{ matrix.os }}
      RUST_BACKTRACE: 1
      RUSTFLAGS: "-C debuginfo=0"
      RUST_VERSION: ${{ matrix.rust_version }}

    runs-on: ${{ matrix.platform.os }}

    steps:
      - name: Checkout sources
        uses: actions/checkout@v3

      - name: Install pNpM
        uses: pnpm/action-setup@v2.2.4
        with:
          version: 7

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
          cache: "pnpm"

      - name: Install pNpM dependencies
        run: pnpm install --frozen-lockfile

      - name: Install musl tools
        if: matrix.os == 'ubuntu-latest'
        run: sudo apt-get install -y musl-tools

      - name: Install Rust ${{ matrix.rust_version }}
        uses: actions-rs/toolchain@v1
        with:
          components: rustfmt clippy
          override: true
          profile: minimal
          target: ${{ matrix.platform.target }}
          toolchain: ${{ matrix.rust_version }}

      - name: Check fmt
        run: cargo fmt -- --check

      - name: Check clippy
        run: cargo clippy -- -D warnings

      - name: Release build
        uses: actions-rs/cargo@v1
        with:
          command: build

      - name: Cache cargo folder
        uses: actions/cache@v2
        with:
          path: ~/.cargo
          key: ${{ matrix.platform.target }}-${{ env.APP_VERSION }}-${{ hashFiles('**/Cargo.lock') }}

      - name: Install Gtk (ubuntu only)
        if: matrix.platform.os == 'ubuntu-latest'
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            build-essential \
            curl \
            libasound2-dev \
            libayatana-appindicator3-dev \
            libgtk-3-dev \
            librsvg2-dev \
            libsoup2.4-dev \
            libssl-dev \
            libwebkit2gtk-4.0-dev \
            wget \

      - name: Check
        run: cargo check --verbose

      - name: Run cargo build for ${{ matrix.platform.target }}
        shell: bash
        run: cd src-tauri/ && cargo $CMD build --verbose --target ${{ matrix.platform.target }} $OPTIONS --features $FEATURES --bin password-generator-pro --release

      - name: Create macOS DMG
        if: contains(matrix.platform.target, 'darwin')
        run: |
          cd src-tauri/
          cargo install cargo-bundle
          cargo bundle

      - name: Create Windows MSI
        if: contains(matrix.platform.target, 'windows')
        run: |
          cd src-tauri/
          cargo install cargo-wix
          cargo wix init
          cargo wix

      - name: Create Linux AppImage
        if: contains(matrix.platform.target, 'linux')
        run: |
          cd src-tauri/
          cargo install cargo-appimage
          cargo appimage

      - name: Create Linux deb
        if: contains(matrix.platform.target, 'linux')
        run: |
          cd src-tauri/
          cargo install cargo-deb
          cargo-deb

      - name: Create Linux rpm
        if: contains(matrix.platform.target, 'linux')
        run: |
          cd src-tauri/
          cargo install cargo-generate-rpm
          cargo generate-rpm --target ${{ matrix.platform.target }}
