name: "Build Password Generator Pro"

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build-binaries:
    name: "${{ matrix.platform.target }}"
    strategy:
      fail-fast: false
      matrix:
        node-version: [16.x]
        rust_version: [stable]
        platform: [macos-latest, ubuntu-latest, windows-latest]

    runs-on: ${{ matrix.platform }}
    steps:
      - uses: actions/checkout@v3
      - uses: pnpm/action-setup@v2.2.4
        with:
          version: 7

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
          cache: "pnpm"

      - name: Install pNpM dependencies
        run: pnpm install --frozen-lockfile

      - name: install Rust stable
        uses: actions-rs/toolchain@v1.0.6
        with:
          toolchain: stable
          target: ${{ matrix.platform.target }}
          profile: minimal
          override: true

      - name: Install dependencies (ubuntu only)
        if: matrix.platform == 'ubuntu-latest'
        run: |
          sudo apt update
          sudo apt install -y \
            build-essential \
            curl \
            gcc-multilib \
            g++-multilib \
            libasound2-dev \
            libasound2-dev:i386 \
            libayatana-appindicator3-dev \
            libgtk-3-dev \
            libgtk-3-dev:i386 \
            librsvg2-dev \
            librsvg2-dev:i386 \
            libsoup2.4-dev \
            libsoup2.4-dev:i386 \
            libssl-dev \
            libssl-dev:i386 \
            libwebkit2gtk-4.0-dev \
            libwebkit2gtk-4.0-dev:i386 \
            patchelf \
            wget \

      - name: Install app dependencies and build it
        run: pnpm run build

      - name: Build
        run: cd src-tauri && cargo build --verbose

      - name: Run tests
        run: cd src-tauri && cargo test --verbose

      - uses: actions/upload-artifact@master
        with:
          name: binaries
          path: ${{ GITHUB.WORKSPACE }}/src-tauri/target/release/bundle/*/password-generator-pro*

      - name: Create release
        run: |
          cd src-tauri
          cargo install cargo-deb
          cargo deb --no-build
          cd target/release/bundle
          mkdir -p password-generator-pro
          mv password-generator-pro_* password-generator-pro
          cd password-generator-pro
          tar -czvf password-generator-pro.tar.gz password-generator-pro_*
          mv password-generator-pro.tar.gz ../../../../
          cd ../../../../
          rm -rf target/release/bundle/password-generator-pro
          mv password-generator-pro.tar.gz target/release/bundle/password-generator-pro
          cd target/release/bundle
          zip -r password-generator-pro.zip password-generator-pro
          cd ../../../../
          rm -rf target/release/bundle/password-generator-pro
          mv target/release/bundle/password-generator-pro.zip target/release/bundle/password-generator-pro
          cd target/release/bundle
          mv password-generator-pro password-generator-pro.deb
          cd ../../../../
          rm -rf target/release/bundle/password-generator-pro
          mv target/release/bundle/password-generator-pro.deb target/release/bundle/password-generator-pro
          cd target/release/bundle
          mv password-generator-pro password-generator-pro.rpm
          cd ../../../../
          rm -rf target/release/bundle/password-generator-pro
          mv target/release/bundle/password-generator-pro.rpm target/release/bundle/password-generator-pro
          cd target/release/bundle
          mv password-generator-pro password-generator-pro.AppImage
          cd ../../../../
          rm -rf target/release/bundle/password-generator-pro
          mv target/release/bundle/password-generator-pro.AppImage target/release/bundle/password-generator-pro
          cd target/release/bundle
          mv password-generator-pro password-generator-pro.exe
          cd ../../../../
          rm -rf target/release/bundle/password-generator-pro
          mv target/release/bundle/password-generator-pro.exe target/release/bundle/password-generator-pro
          cd target/release/bundle
          mv password-generator-pro password-generator-pro.dmg
          cd ../../../../
          rm -rf target/release/bundle/password-generator-pro
          mv target/release/bundle/password-generator-pro.dmg target/release/bundle/password-generator-pro
          cd target/release/bundle
          mv password-generator-pro password-generator-pro.msi
          cd ../../../../
          rm -rf target/release/bundle/password-generator-pro
          mv target/release/bundle/password-generator-pro.msi target/release/bundle/password-generator-pro
          cd target/release/bundle
          mv password-generator-pro password-generator-pro.snap

